### ISSUE TITLE
2 event-entity

### ISSUE THREAD

**Issue by uiytt** [SkriptHub/SkriptHub#13]
In vehicle event : 
https://skripthub.net/docs/?id=1061
https://skripthub.net/docs/?id=1062
etc...
there is 2 event-entity, is it normal ?

**Comment by Blueyescat** [comment]
Hmm, it should be about how Skript registers event values for the vehicle events..
https://github.com/SkriptLang/Skript/blob/b457dfb16e4014d930ae72194ca8a50f27dd920f/src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java#L691-L720

Probably because it registers event value for Vehicle, but there is no vehicle type in Skript so it would shown as entity. It also registers entity for passenger of the vehicle.

But can be fixed for docs.

https://github.com/SkriptLang/Skript/issues/ 1337

**Comment by eyesniper2** [comment]
Closing as the fix is being discussed here: https://github.com/SkriptLang/Skript/issues/1337
